// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/common-healthcheck (interfaces: FlakiClient)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// FlakiClient is a mock of FlakiClient interface
type FlakiClient struct {
	ctrl     *gomock.Controller
	recorder *FlakiClientMockRecorder
}

// FlakiClientMockRecorder is the mock recorder for FlakiClient
type FlakiClientMockRecorder struct {
	mock *FlakiClient
}

// NewFlakiClient creates a new mock instance
func NewFlakiClient(ctrl *gomock.Controller) *FlakiClient {
	mock := &FlakiClient{ctrl: ctrl}
	mock.recorder = &FlakiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *FlakiClient) EXPECT() *FlakiClientMockRecorder {
	return m.recorder
}

// NextID mocks base method
func (m *FlakiClient) NextID(arg0 context.Context) (string, error) {
	ret := m.ctrl.Call(m, "NextID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextID indicates an expected call of NextID
func (mr *FlakiClientMockRecorder) NextID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextID", reflect.TypeOf((*FlakiClient)(nil).NextID), arg0)
}
